// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var LiveReloadContext, OPTIONS, Path, debug, dreamopt, fs;

  debug = require('debug')('livereload:cli');

  Path = require('path');

  fs = require('fs');

  dreamopt = require('dreamopt');

  LiveReloadContext = require('./context');

  OPTIONS = ['Commands for interactive usage:', '  watch', 'Other commands:', '  rpc', 'General options:'];

  exports.run = function(argv) {
    var context, options;
    options = dreamopt(OPTIONS, {
      loadCommandSyntax: function(name) {
        return require("./commands/" + (name.replace(/\s/g, '-'))).usage;
      }
    });
    debug(JSON.stringify(options));
    context = new LiveReloadContext();
    return require("./commands/" + options.command).run(options, context);
  };

}).call(this);
