// Generated by IcedCoffeeScript 1.3.1c
(function() {
  var fill, now;

  fill = function(n) {
    if ((0 < n && n < 10)) {
      return "0" + n;
    } else {
      return "" + n;
    }
  };

  now = function() {
    var H, M, S, d, date, m, y;
    date = new Date();
    y = date.getFullYear();
    m = fill(1 + date.getMonth());
    d = fill(date.getDate());
    H = fill(date.getHours());
    M = fill(date.getMinutes());
    S = fill(date.getSeconds());
    return "" + y + "-" + m + "-" + d + " " + H + ":" + M + ":" + S;
  };

  exports.omg = function(message) {
    return process.stderr.write("" + (now()) + " node OMG: " + (message.trim()) + "\n");
  };

  exports.wtf = function(message) {
    return process.stderr.write("" + (now()) + " node WTF: " + (message.trim()) + "\n");
  };

  exports.fyi = function(message) {
    return process.stderr.write("" + (now()) + " node: " + (message.trim()) + "\n");
  };

}).call(this);
