// Generated by IcedCoffeeScript 1.3.1c
(function() {
  var EventEmitter, createApiTree, createRemoteApiTree, fs, path,
    __slice = [].slice;

  require('sugar');

  fs = require('fs');

  path = require('path');

  EventEmitter = require('events').EventEmitter;

  createApiTree = require('apitree').createApiTree;

  createRemoteApiTree = require('../lib/remoteapitree').createRemoteApiTree;

  exports.createEnvironment = function(options, context) {
    var LR, messages;
    LR = createApiTree(context.paths.rpc);
    LR.events = new EventEmitter();
    messages = JSON.parse(fs.readFileSync(path.join(__dirname, 'client-messages.json'), 'utf8'));
    messages.pop();
    LR.client = createRemoteApiTree(messages, function(msg) {
      return function() {
        var args, _ref;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return (_ref = LR.rpc).send.apply(_ref, [msg].concat(__slice.call(args)));
      };
    });
    return LR;
  };

}).call(this);
