platform :osx, '10.10'
use_frameworks!

workspace 'LRExperiments'
project 'LRExperiments/LRExperiments.xcodeproj'

target 'LRExperiments' do
    pod 'PromiseKit', :subspecs => %w(CorePromise DietFoundation SystemConfiguration)
end
