// Generated by IcedCoffeeScript 1.3.1c
(function() {
  var createProjectViewModel, createViewModel, createWelcomeViewModel, publishViewModel, _selectedProject;

  _selectedProject = null;

  createWelcomeViewModel = function() {
    return {
      pane: 'welcome'
    };
  };

  createProjectViewModel = function() {
    return {
      pane: 'project',
      name: _selectedProject.name
    };
  };

  createViewModel = function() {
    if (_selectedProject === null) {
      return createWelcomeViewModel();
    } else {
      return createProjectViewModel();
    }
  };

  publishViewModel = function() {
    return LR.client.mainwnd.rpane.setData(createViewModel());
  };

  exports.setSelectedProject = function(_arg, callback) {
    var project, projectId;
    projectId = _arg.projectId;
    if (project = LR.projects.findById(projectId)) {
      _selectedProject = project;
    } else {
      _selectedProject = null;
    }
    publishViewModel();
    return callback(null);
  };

}).call(this);
