// Generated by IcedCoffeeScript 1.3.1c
(function() {
  var PluginManager, _pluginManager;

  PluginManager = require('../lib/plugin').PluginManager;

  _pluginManager = null;

  exports.init = function(pluginFolders, callback) {
    _pluginManager = new PluginManager(pluginFolders);
    return _pluginManager.rescan(callback);
  };

}).call(this);
