// Generated by IcedCoffeeScript 1.3.1c
(function() {

  exports.api = {
    add: function(_arg, callback) {
      var path;
      path = _arg.path;
    },
    remove: function(_arg, callback) {
      var projectId;
      projectId = _arg.projectId;
    },
    changeDetected: function(_arg, callback) {
      var changes, id;
      id = _arg.id, changes = _arg.changes;
    }
  };

}).call(this);
